#Mappable object
# a={"name":"ram","contact":"98239000","address":"kathmandu"}
# print(a)
# print(hash("name")) 
# profile={"name":"hari","contact":"9889898","address":"kathmandu"}
# p=profile.copy()
# print(p)
# print(profile)
# p.clear()
# print(p,"f")
# p={}
# a={"username","password","email"}
# p=p.fromkeys(a,"sabin",23232,"sabin@gmail.com")
# print(p)
# profile={"name":"shyam","address":"ktm"}
# print(profile.get(name))
# print() 
# print(profile.items())
# print(profile.keys())
# print(profile.values())
# print(profile.pop("name"))
# print(profile)
# print(profile.popitem())
# print(profile.setdefault("name","shyam"))
# profile.setdefault("email","shyam@gmail.com")
# print(profile)